package com.jframes;

import StudentDaoImpl.StudentDaoImpl;
import com.dao.StudentDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUKHTIAR ALI CHANDIO
 */
public class StudentRegisterationtFormJFrame extends javax.swing.JFrame {

     StudentDao stdDao=new StudentDaoImpl();
 
    public StudentRegisterationtFormJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentPicPanelOne = new javax.swing.JPanel();
        StudentsLabel = new javax.swing.JLabel();
        StudentInformationPanelTwo = new javax.swing.JPanel();
        StudentRegisteratinLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        fatherNameLabel = new javax.swing.JLabel();
        fathernameTextField = new javax.swing.JTextField();
        MotherNameLabel = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        cnicLabel = new javax.swing.JLabel();
        cnicTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        provComboBox = new javax.swing.JComboBox();
        countryLabel = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox();
        dateofregisterLabel = new javax.swing.JLabel();
        dateofbirthTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        contactNumberTextField = new javax.swing.JTextField();
        Reading = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        Writing = new javax.swing.JCheckBox();
        painting = new javax.swing.JCheckBox();
        Music = new javax.swing.JCheckBox();
        Singing = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentPicPanelOne.setBackground(new java.awt.Color(0, 153, 153));

        StudentsLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\MUKHTIAR ALI CHANDIO\\Desktop\\Student Mangent System Pics\\stdspic3.jpg")); // NOI18N

        javax.swing.GroupLayout StudentPicPanelOneLayout = new javax.swing.GroupLayout(StudentPicPanelOne);
        StudentPicPanelOne.setLayout(StudentPicPanelOneLayout);
        StudentPicPanelOneLayout.setHorizontalGroup(
            StudentPicPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPicPanelOneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(StudentsLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        StudentPicPanelOneLayout.setVerticalGroup(
            StudentPicPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPicPanelOneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StudentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        StudentInformationPanelTwo.setBackground(new java.awt.Color(204, 204, 204));

        StudentRegisteratinLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        StudentRegisteratinLabel.setText("Student Registeration Form");

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstNameLabel.setText("First Name");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel.setText("Gender");

        maleRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maleRadioButton.setText("Male");

        femaleRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        femaleRadioButton.setText("Female");

        fatherNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fatherNameLabel.setText("Father Name");

        fathernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernameTextFieldActionPerformed(evt);
            }
        });

        MotherNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MotherNameLabel.setText("email Id");

        cnicLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnicLabel.setText("Cnic");

        cnicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicTextFieldActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cityLabel.setText("Contact Number");

        provinceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        provinceLabel.setText("Province");

        provComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sindh", "Punjab", "Kpk", "Balochistan", "GilgitBaltistan", "AzadKashmir" }));
        provComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provComboBoxActionPerformed(evt);
            }
        });

        countryLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        countryLabel.setText("Country");

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pakistan", "London", "America", "England", "Germany", "France", "China" }));

        dateofregisterLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateofregisterLabel.setText("Date of Register");

        dateofbirthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofbirthTextFieldActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("Add Data");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Surname");

        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });

        Reading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reading.setText("Reading");
        Reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadingActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Hobbies");

        Writing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Writing.setText("Writing");

        painting.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        painting.setText("painting");

        Music.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Music.setText("Music");
        Music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicActionPerformed(evt);
            }
        });

        Singing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Singing.setText("Singing");
        Singing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Address");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        javax.swing.GroupLayout StudentInformationPanelTwoLayout = new javax.swing.GroupLayout(StudentInformationPanelTwo);
        StudentInformationPanelTwo.setLayout(StudentInformationPanelTwoLayout);
        StudentInformationPanelTwoLayout.setHorizontalGroup(
            StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(StudentRegisteratinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(provinceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(provComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                                .addComponent(dateofregisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateofbirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reading)
                                .addGap(41, 41, 41)
                                .addComponent(Writing)
                                .addGap(37, 37, 37)
                                .addComponent(painting)
                                .addGap(31, 31, 31)
                                .addComponent(Singing)
                                .addGap(17, 17, 17)
                                .addComponent(Music))))
                    .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(MotherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(lastNameLabel))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentInformationPanelTwoLayout.createSequentialGroup()
                                    .addComponent(fatherNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fathernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(surnameTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentInformationPanelTwoLayout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(cnicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        StudentInformationPanelTwoLayout.setVerticalGroup(
            StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(StudentRegisteratinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lastNameLabel))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fathernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fatherNameLabel))
                    .addComponent(cnicLabel)
                    .addComponent(cnicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel)
                    .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MotherNameLabel)
                        .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(maleRadioButton))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(femaleRadioButton))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(provinceLabel))
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(provComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofbirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofregisterLabel))
                .addGap(30, 30, 30)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Reading)
                        .addComponent(jLabel9))
                    .addComponent(Writing)
                    .addComponent(painting)
                    .addComponent(Singing)
                    .addComponent(Music))
                .addGap(29, 29, 29)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StudentInformationPanelTwoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(StudentInformationPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(StudentPicPanelOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentInformationPanelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentPicPanelOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StudentInformationPanelTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void fathernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernameTextFieldActionPerformed

    private void cnicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicTextFieldActionPerformed

    private void dateofbirthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofbirthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
         
        String firstName = firstNameTextField.getText();
        String fatherName= fathernameTextField.getText();
        String lastName=lastNameTextField.getText();
        String surname=surnameTextField.getText();
        String cnic=cnicTextField.getText();
        String contactNumber=contactNumberTextField.getText();
        String email=emailIdTextField.getText();
        String dateOfbirth=dateofbirthTextField.getText();
        String selectedprovince = provComboBox.getSelectedItem().toString();
        String selectedcountry = countryComboBox.getSelectedItem().toString();
        String address=addressTextArea.getText();
        String gender = "";
        if (maleRadioButton.isSelected()) {
          gender = "Male";
        }else if (femaleRadioButton.isSelected()) {
          gender = "Female";
        }       
        List<String> selectedHobbies = new ArrayList<>();
        if (Reading.isSelected()) selectedHobbies.add("Reading");
        if (Writing.isSelected()) selectedHobbies.add("Writing");
        if (painting.isSelected()) selectedHobbies.add("painting");
        if (Music.isSelected()) selectedHobbies.add("Music");
        if (Singing.isSelected()) selectedHobbies.add("Singing");
        // Join list into comma-separated string
        String hobbies = String.join(",", selectedHobbies);
    
        
        stdDao.addStudent(firstName, lastName, fatherName, dateOfbirth, surname, cnic, contactNumber, email, gender, selectedHobbies, selectedprovince, selectedcountry, address);
        
       // stdDao.addStudent(firstName, lastName, lastName, dateOfbirth, surname, cnic, contactNumber, email, gender, selectedHobbies, address);
        
    //System.out.print(selectedItem1);

    //System.out.print(selectedItem2);
    
    //System.out.print(firstName+lastName+surname+cnic+contactNumber+email+gender+address+dateOfbirth+selectedHobbies);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void provComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provComboBoxActionPerformed

    private void ReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReadingActionPerformed

    private void MusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicActionPerformed

    private void SingingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingingActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        
        hide();
        
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        //this.stdIdTextField.setText("");
        this.firstNameTextField.setText("");
        this.dateofbirthTextField.setText("");
        this.fathernameTextField.setText("");
        this.lastNameTextField.setText("");
        this.surnameTextField.setText("");
        this.cnicTextField.setText("");
        this.surnameTextField.setText("");
        this.contactNumberTextField.setText("");
        this.emailIdTextField.setText("");
        this.addressTextArea.setText("");

    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterationtFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterationtFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterationtFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegisterationtFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegisterationtFormJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel MotherNameLabel;
    private javax.swing.JCheckBox Music;
    private javax.swing.JCheckBox Reading;
    private javax.swing.JCheckBox Singing;
    private javax.swing.JPanel StudentInformationPanelTwo;
    private javax.swing.JPanel StudentPicPanelOne;
    private javax.swing.JLabel StudentRegisteratinLabel;
    private javax.swing.JLabel StudentsLabel;
    private javax.swing.JCheckBox Writing;
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel cnicLabel;
    private javax.swing.JTextField cnicTextField;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JComboBox countryComboBox;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField dateofbirthTextField;
    private javax.swing.JLabel dateofregisterLabel;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JTextField fathernameTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JCheckBox painting;
    private javax.swing.JComboBox provComboBox;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
}
