/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jframes;

import StudentDaoImpl.StudentDaoImpl;
import com.beans.Student;
import com.dao.StudentDao;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MUKHTIAR ALI CHANDIO
 */
public class ViewStudentData extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentData
     */
    public ViewStudentData() {
        initComponents();
    }

    
   /*public  void  getStudentdataByid(){
    
        
            StudentDao daoImpl = new StudentDaoImpl();

        
          DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "ID", "First Name", "Last Name", "Surname", "CNIC",  "Contact No", "Email",  "Gender", "Hobbies", "Address"
        });

        List<Student> students = new StudentDaoImpl().getAllStudents();
 
        
        for (Student s : students) {
            model.addRow(new Object[]{
                s.getId(), s.getFirstName(), s.getLastName(), s.getSurname(),
                s.getCnic(),  s.getContactNo(), s.getEmailId(), s.getGender(), s.getHobbies(), s.getAddress(),
            });
        }

         //System.out.println("FirstName:"+firstName);
        showDataTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                int selectedRow = showDataTable.getSelectedRow();

                if (selectedRow != -1) {
                    // Get values from the selected row
                    Object id = showDataTable.getValueAt(selectedRow, 0);
                    Object firstName = showDataTable.getValueAt(selectedRow, 1);
                    Object lastName = showDataTable.getValueAt(selectedRow, 2);
                    Object surname = showDataTable.getValueAt(selectedRow, 3);
                    Object cnic = showDataTable.getValueAt(selectedRow, 4);
                    Object contactNo = showDataTable.getValueAt(selectedRow, 5);
                    Object email = showDataTable.getValueAt(selectedRow, 6);
                   Object gender=showDataTable.getValueAt(selectedRow, 7);

   
                    Object hobbies=showDataTable.getValueAt(selectedRow, 8);
                    Object address = showDataTable.getValueAt(selectedRow, 9);

                    // Set the values in the JTextFields
                    stdIdTextField.setText(id.toString());
                    firstNameTextField.setText(firstName.toString());
                    lastNameTextField.setText(lastName.toString());
                    surnameTextField.setText(surname.toString());
                    cnicTextField.setText(cnic.toString());
                    contactNumberTextField.setText(contactNo.toString());
                    emailIdTextField.setText(email.toString());
                     maleRadioButton.setText(gender.toString());
                     femaleRadioButton.setText(gender.toString());
                    
                    addressTextArea.setText(address.toString());
                    

                    
                }
            }
        });
    
    
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteDataButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDataTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 51));

        deleteDataButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteDataButton.setText("Delete Data");
        deleteDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataButtonActionPerformed(evt);
            }
        });

        showDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        showDataTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                showDataTableAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(showDataTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("    Student  Show  Data");

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(deleteDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 302, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataButtonActionPerformed
        
   int selectedRow = showDataTable.getSelectedRow();
 
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) showDataTable.getModel();
        Object idObj = model.getValueAt(selectedRow, 0); // Get ID from column 0

        if (idObj != null) {
            int studentId = Integer.parseInt(idObj.toString());

            // Confirm deletion
            int confirm = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete student with ID: " + studentId + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                // Delete from DB
                StudentDaoImpl stdDao = new StudentDaoImpl();
                boolean deleted = stdDao.deleteStudentdataByid(studentId);
                      
                //stdDao.deleteStudentdataByid(studentId);
                if (deleted) {
                    model.removeRow(selectedRow); // Delete from table
                    JOptionPane.showMessageDialog(null, "Student deleted successfully.");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to delete student.");
                }
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a row to delete.");
    }

        
    }//GEN-LAST:event_deleteDataButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        hide();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void showDataTableAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_showDataTableAncestorMoved

        
             
    StudentDao daoImpl = new StudentDaoImpl();
    List<Student> students = daoImpl.getAllStudents();
   
    
    
    

  DefaultTableModel model = new DefaultTableModel();
    
    // Add column names
    model.addColumn("ID");
    model.addColumn("First Name");
    model.addColumn("Last Name");
    model.addColumn("Surname");
    model.addColumn("CNIC");
    model.addColumn("Contact No");
    model.addColumn("Email");
    
    model.addColumn("Gender");
    model .addColumn("Hobbies");
    model.addColumn("Address");
    // Add rows
    for (Student s : students) {
        model.addRow(new Object[]{
            s.getId(),
            s.getFirstName(),
            s.getLastName(),
            s.getSurname(),
            s.getCnic(),
            s.getContactNo(),
             s.getEmailId(),
            s.getGender(),
           s.getHobbies(),
           
            s.getAddress(),
                
        });
    }

    // Set model to table
    showDataTable.setModel(model);
     // System.out.print("ModelObject:"+model);
        
        
        
   
        
        
        
        
   
        
        
        
    }//GEN-LAST:event_showDataTableAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteDataButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showDataTable;
    // End of variables declaration//GEN-END:variables
}
